CFLAGS = /nologo /W4 /EHsc /Za /DDEBUG__

main.exe: main.obj add.obj
	$(CPP) $(CFLAGS) /Fe$@ $**

main.obj: main.c
	$(CPP) $(CFLAGS) /c /Fo$@ $**

add.obj: add.c
	$(CPP) $(CFLAGS) /c /Fo$@ $**

clean:
	del *.obj *.exe
