L = lib /nologo
CFLAGS = /nologo /W3

all: bounds_static.exe

bounds_static.exe: bounds.obj bounds_static.lib
	cl /Fe$@ $**

bounds_static.lib: max.obj min.obj
	$(L) /out:$@ $**

min.obj: min.c 
	$(CC) $(CFLAGS) /c /Fo$@ $**

max.obj: max.c 
	$(CC) $(CFLAGS) /c /Fo$@ $**

bounds.obj: bounds.c
	$(CC) $(CFLAGS) /c /Fo$@ $**

clean:
	del /Q /F *.obj *.lib *.dll *.exe
